[tool.poetry]
name = "sachi"
version = "0.2.2-dev"
description = "Terminal media files renamer (FileBot alternative)"
authors = ["NextFire <git@yuru.moe>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/NextFire/sachi"

[tool.poetry.scripts]
sachi = "sachi:cli_app"

[tool.poetry.dependencies]
python = "~3.12"
typer-slim = { version = "0.12.5", extras = ["standard"] }
textual = "0.79.1"
tomlkit = "0.13.2"
pydantic = "2.9.2"
aiohttp = { version = "3.10.5", extras = ["speedups"] }
yarl = "1.11.1"
backoff = "2.2.1"
jinja2 = "3.1.4"
pymediainfo = "6.1.0"
guessit = "3.8.0"
setuptools = { version = "75.1.0", markers = "python_version >= '3.12'" } # guessit

[tool.poetry.group.dev.dependencies]
pyright = "1.1.381"
ruff = "0.6.7"
textual-dev = "1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"]
