[tool.poetry]
name = "sachi"
version = "0.1.0-dev"
description = ""
authors = ["NextFire <git@yuru.moe>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/NextFire/sachi"

[tool.poetry.scripts]
sachi = "sachi:cli_app"

[tool.poetry.dependencies]
python = "~3.12"
typer = {extras = ["all"], version = "^0.9.0"}
textual = "^0.47.1"
tomlkit = "^0.12.3"
pydantic = "^2.5.3"
aiohttp = {extras = ["speedups"], version = "^3.9.2"}
yarl = "^1.9.4"
backoff = "^2.2.1"
jinja2 = "^3.1.3"
pymediainfo = "^6.1.0"
guessit = "^3.8.0"
setuptools = {version = "^69.0.3", markers = "python_version >= '3.12'"}  # required for guessit

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.348"
ruff = "^0.1.14"
textual-dev = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
extend-select = ["I"]
