[project]
name = "sachi"
version = "0.3.1-dev"
description = "Terminal media files renamer (FileBot alternative)"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "NextFire", email = "git@yuru.moe" }]
requires-python = ">=3.12"
dependencies = [
    "typer==0.12.5",
    "textual==0.83.0",
    "tomlkit==0.13.2",
    "pydantic==2.9.2",
    "aiohttp[speedups]==3.10.10",
    "yarl==1.15.3",
    "backoff==2.2.1",
    "jinja2==3.1.4",
    "pymediainfo==6.1.0",
    "guessit==3.8.0",
    "setuptools==75.1.0",         # guessit
]

[tool.uv]
dev-dependencies = ["pyright==1.1.384", "ruff==0.6.9", "textual-dev==1.6.1"]

[project.scripts]
sachi = "sachi:cli_app"

[project.urls]
Homepage = "https://github.com/NextFire/sachi"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
pythonVersion = "3.12"

[tool.ruff.lint]
extend-select = ["I"]
