[project]
name = "sachi"
dynamic = ["version"]
description = "Terminal media files renamer (FileBot alternative)"
readme = "README.md"
license = "MIT"
authors = [{ name = "NextFire", email = "git@yuru.moe" }]
requires-python = ">=3.12"
dependencies = [
    "typer==0.15.1",
    "textual==2.1.2",
    "tomlkit==0.13.2",
    "pydantic==2.10.6",
    "aiohttp[speedups]==3.11.13",
    "yarl==1.18.3",
    "backoff==2.2.1",
    "jinja2==3.1.5",
    "pymediainfo==7.0.1",
    "guessit==3.8.0",
    # guessit requirement
    "setuptools==75.8.2",
]

[dependency-groups]
dev = ["pyright==1.1.395", "ruff==0.9.8", "textual-dev==1.7.0"]

[project.scripts]
sachi = "sachi:cli_app"

[project.urls]
homepage = "https://github.com/NextFire/sachi"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.pyright]
pythonVersion = "3.12"

[tool.ruff.lint]
extend-select = ["I"]
