[project]
name = "sachi"
dynamic = ["version"]
description = "Terminal media files renamer (FileBot alternative)"
readme = "README.md"
license = "MIT"
authors = [{ name = "NextFire", email = "git@yuru.moe" }]
requires-python = ">=3.12"
dependencies = [
    "typer==0.12.5",
    "textual==0.85.1",
    "tomlkit==0.13.2",
    "pydantic==2.9.2",
    "aiohttp[speedups]==3.10.10",
    "yarl==1.17.0",
    "backoff==2.2.1",
    "jinja2==3.1.4",
    "pymediainfo==6.1.0",
    "guessit==3.8.0",
    # guessit requirement
    "setuptools==75.3.0",
]

[dependency-groups]
dev = ["pyright==1.1.387", "ruff==0.7.1", "textual-dev==1.6.1"]

[project.scripts]
sachi = "sachi:cli_app"

[project.urls]
homepage = "https://github.com/NextFire/sachi"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.pyright]
pythonVersion = "3.12"

[tool.ruff.lint]
extend-select = ["I"]
